// Loads all sample stations (matching src/data/stations.js shape) into MongoDB.
// Run with: node utils/seed.js
require('dotenv').config();
const mongoose = require('mongoose');
const connectDB = require('../config/db');
const Station = require('../models/StationModel');

const sampleStations = [
  {
    slug: 'one-galle-face',
    name: 'One Galle Face Mall',
    address: 'Colombo 05, Sri Lanka',
    lat: 6.9218, lng: 79.8478,
    rating: 4.6, reviews: 142,
    status: 'available',
    distanceMins: 30, distanceKm: 1.2,
    pluggedAvailable: 4, pluggedTotal: 6,
    tags: ['CCS2', 'Type 2', 'AC', 'DC Fast'],
    image: '', images: [],
    bays: ['available', 'available', 'limited', 'unavailable'],
    baysDetail: [
      { name: 'Bay 1', status: 'available', label: 'Available' },
      { name: 'Bay 2', status: 'available', label: 'Available' },
      { name: 'Bay 3', status: 'limited', label: 'Limited' },
      { name: 'Bay 4', status: 'unavailable', label: 'Unavailable' },
    ],
    openHours: 'Open 24 hrs',
    pricingText: 'LKR 62 / kWh', idleFeeText: 'LKR 12 / min',
    parkingText: 'Mall Rate', amenitiesText: 'Wi-Fi, Shop',
    accessType: 'Public · Mall Parking',
    network: 'Evora Power · Rapid DC (100kW+)',
    priceHeadline: 'LKR 62.00',
    rates: { fast: 45, slow: 20 },
    maxChargingSpeedKw: 150, portsCount: 6,
    supportedModels: ['Tesla Model 3/Y', 'Nissan Leaf', 'BYD Atto 3', 'Hyundai Ioniq 5'],
    amenities: ['wifi', 'cafe', 'parking', 'restroom', 'shopping'],
    connectors: [
      { name: 'Tesla NACS', kw: '50kW', available: true },
      { name: 'CHAdeMO DC', kw: '50kW', available: true },
      { name: 'CCS Combo 2', kw: '50kW – 150kW', available: false },
      { name: 'Type 2 AC', kw: '3.7kW – 22kW', available: false },
    ],
  },
  {
    slug: 'colombo-city-center',
    name: 'Colombo City Center Mall',
    address: '137, Sir James Peiris Mawatha, Colombo 00200',
    lat: 6.9270, lng: 79.8612,
    rating: 4.3, reviews: 98,
    status: 'soon',
    distanceMins: 18, distanceKm: 3.4,
    pluggedAvailable: 2, pluggedTotal: 6,
    tags: ['Type 2', 'CCS2', 'AC', 'DC Fast'],
    image: '', images: [],
    bays: ['available', 'available', 'limited', 'unavailable'],
    baysDetail: [
      { name: 'Bay 1', status: 'available', label: 'Available' },
      { name: 'Bay 2', status: 'available', label: 'Available' },
      { name: 'Bay 3', status: 'limited', label: 'Limited' },
      { name: 'Bay 4', status: 'unavailable', label: 'Unavailable' },
    ],
    openHours: 'Open 24 hrs',
    pricingText: 'LKR 58 / kWh', idleFeeText: 'LKR 10 / min',
    parkingText: 'Free', amenitiesText: 'Wi-Fi, Cafe',
    accessType: 'Public · Mall Parking',
    network: 'Evora Power · Fast DC (60kW+)',
    priceHeadline: 'LKR 58.00',
    rates: { fast: 42, slow: 18 },
    maxChargingSpeedKw: 60, portsCount: 6,
    supportedModels: ['Nissan Leaf', 'Hyundai Kona', 'MG ZS EV', 'BYD Atto 3'],
    amenities: ['wifi', 'cafe', 'parking', 'restroom', 'shopping'],
    connectors: [
      { name: 'Type 2 AC', kw: '3.7kW – 22kW', available: true },
      { name: 'CCS Combo 2', kw: '50kW – 150kW', available: true },
      { name: 'Tesla NACS', kw: '50kW', available: false },
      { name: 'CHAdeMO DC', kw: '50kW', available: false },
    ],
  },
  {
    slug: 'independence-arcade',
    name: 'Independence Arcade',
    address: 'Colombo 07, Sri Lanka',
    lat: 6.9058, lng: 79.8607,
    rating: 4.0, reviews: 54,
    status: 'full',
    distanceMins: 42, distanceKm: 5.1,
    pluggedAvailable: 0, pluggedTotal: 4,
    tags: ['CCS2', 'Type 2', 'AC', 'DC Fast'],
    image: '', images: [],
    bays: ['unavailable', 'unavailable', 'limited', 'unavailable'],
    baysDetail: [
      { name: 'Bay 1', status: 'unavailable', label: 'Unavailable' },
      { name: 'Bay 2', status: 'unavailable', label: 'Unavailable' },
      { name: 'Bay 3', status: 'limited', label: 'Limited' },
      { name: 'Bay 4', status: 'unavailable', label: 'Unavailable' },
    ],
    openHours: 'Open 24 hrs',
    pricingText: 'LKR 64 / kWh', idleFeeText: 'LKR 15 / min',
    parkingText: 'Free', amenitiesText: 'Cafe, Park',
    accessType: 'Public · Street Parking',
    network: 'Evora Power · Rapid DC (100kW+)',
    priceHeadline: 'LKR 64.00',
    rates: { fast: 47, slow: 21 },
    maxChargingSpeedKw: 150, portsCount: 4,
    supportedModels: ['Tesla Model 3/Y', 'BYD Atto 3', 'Hyundai Ioniq 5'],
    amenities: ['parking', 'security'],
    connectors: [
      { name: 'CCS Combo 2', kw: '50kW – 150kW', available: false },
      { name: 'Tesla NACS', kw: '50kW', available: false },
      { name: 'Type 2 AC', kw: '3.7kW – 22kW', available: false },
      { name: 'CHAdeMO DC', kw: '50kW', available: false },
    ],
  },
  {
    slug: 'havelock-city',
    name: 'Havelock City Mall',
    address: 'Colombo 05, Sri Lanka',
    lat: 6.8862, lng: 79.8636,
    rating: 4.5, reviews: 120,
    status: 'available',
    distanceMins: 25, distanceKm: 2.6,
    pluggedAvailable: 5, pluggedTotal: 6,
    tags: ['Type 2', 'CCS2', 'AC', 'DC Fast'],
    image: '', images: [],
    bays: ['available', 'available', 'limited', 'unavailable'],
    baysDetail: [
      { name: 'Bay 1', status: 'available', label: 'Available' },
      { name: 'Bay 2', status: 'available', label: 'Available' },
      { name: 'Bay 3', status: 'limited', label: 'Limited' },
      { name: 'Bay 4', status: 'unavailable', label: 'Unavailable' },
    ],
    openHours: 'Open 24 hrs',
    pricingText: 'LKR 60 / kWh', idleFeeText: 'LKR 10 / min',
    parkingText: 'Free', amenitiesText: 'Wi-Fi, Cafe',
    accessType: 'Public · Mall Parking',
    network: 'Evora Power · Rapid DC (100kW+)',
    priceHeadline: 'LKR 60.00',
    rates: { fast: 44, slow: 19 },
    maxChargingSpeedKw: 120, portsCount: 6,
    supportedModels: ['Tesla Model 3/Y', 'Nissan Leaf', 'Hyundai Ioniq 5', 'MG ZS EV'],
    amenities: ['wifi', 'cafe', 'parking', 'restroom', 'shopping'],
    connectors: [
      { name: 'Type 2 AC', kw: '3.7kW – 22kW', available: true },
      { name: 'Tesla NACS', kw: '50kW', available: true },
      { name: 'CCS Combo 2', kw: '50kW – 150kW', available: true },
      { name: 'CHAdeMO DC', kw: '50kW', available: false },
    ],
  },
  {
    slug: 'morven-hotel',
    name: 'Morven Hotel Colombo',
    address: 'Union Place, Colombo 02, Sri Lanka',
    lat: 6.9186, lng: 79.8531,
    rating: 4.4, reviews: 76,
    status: 'available',
    distanceMins: 22, distanceKm: 2.0,
    pluggedAvailable: 2, pluggedTotal: 2,
    tags: ['Type 2', 'CCS2', 'AC', 'DC Fast'],
    image: '', images: [],
    bays: ['available', 'available', 'limited', 'unavailable'],
    baysDetail: [
      { name: 'Bay 1', status: 'available', label: 'Available' },
      { name: 'Bay 2', status: 'available', label: 'Available' },
      { name: 'Bay 3', status: 'limited', label: 'Limited' },
      { name: 'Bay 4', status: 'unavailable', label: 'Unavailable' },
    ],
    openHours: 'Open 24 hrs',
    pricingText: 'LKR 55 / kWh', idleFeeText: 'LKR 8 / min',
    parkingText: 'Free', amenitiesText: 'Wi-Fi, Hotel',
    accessType: 'Public · Hotel Parking',
    network: 'Green EV · Fast AC (22kW)',
    priceHeadline: 'LKR 55.00',
    rates: { fast: 40, slow: 17 },
    maxChargingSpeedKw: 22, portsCount: 2,
    supportedModels: ['Nissan Leaf', 'MG ZS EV', 'Hyundai Kona'],
    amenities: ['wifi', 'cafe', 'parking', 'restroom'],
    connectors: [
      { name: 'Type 2 AC', kw: '7kW – 22kW', available: true },
      { name: 'CCS Combo 2', kw: '22kW', available: true },
    ],
  },
  {
    slug: 'vedrive-station',
    name: 'VEDRIVE Charging Station',
    address: 'Rajagiriya, Sri Lanka',
    lat: 6.9107, lng: 79.8878,
    rating: 4.2, reviews: 39,
    status: 'available',
    distanceMins: 28, distanceKm: 4.3,
    pluggedAvailable: 3, pluggedTotal: 4,
    tags: ['CCS2', 'Type 2', 'AC', 'DC Fast'],
    image: '', images: [],
    bays: ['available', 'available', 'limited', 'unavailable'],
    baysDetail: [
      { name: 'Bay 1', status: 'available', label: 'Available' },
      { name: 'Bay 2', status: 'available', label: 'Available' },
      { name: 'Bay 3', status: 'limited', label: 'Limited' },
      { name: 'Bay 4', status: 'unavailable', label: 'Unavailable' },
    ],
    openHours: 'Open 24 hrs',
    pricingText: 'LKR 59 / kWh', idleFeeText: 'LKR 10 / min',
    parkingText: 'Free', amenitiesText: 'Wi-Fi, Shop',
    accessType: 'Public · Street Parking',
    network: 'VEDRIVE · Dual DC (60kW)',
    priceHeadline: 'LKR 59.00',
    rates: { fast: 43, slow: 19 },
    maxChargingSpeedKw: 60, portsCount: 4,
    supportedModels: ['Tesla Model 3/Y', 'BYD Atto 3', 'Hyundai Ioniq 5'],
    amenities: ['parking', 'security'],
    connectors: [
      { name: 'CCS Combo 2', kw: '60kW', available: true },
      { name: 'Type 2 AC', kw: '7kW – 22kW', available: true },
    ],
  },
  {
    slug: 'volt-charge-cod',
    name: 'Volt Charge - COD',
    address: 'Kollupitiya, Colombo 03, Sri Lanka',
    lat: 6.9147, lng: 79.8481,
    rating: 4.1, reviews: 279,
    status: 'available',
    distanceMins: 20, distanceKm: 3.7,
    pluggedAvailable: 2, pluggedTotal: 4,
    tags: ['Type 2', 'CCS2', 'AC', 'DC Fast'],
    image: '', images: [],
    bays: ['available', 'available', 'limited', 'unavailable'],
    baysDetail: [
      { name: 'Bay 1', status: 'available', label: 'Available' },
      { name: 'Bay 2', status: 'available', label: 'Available' },
      { name: 'Bay 3', status: 'limited', label: 'Limited' },
      { name: 'Bay 4', status: 'unavailable', label: 'Unavailable' },
    ],
    openHours: 'Open 24 hrs',
    pricingText: 'LKR 85 / kWh', idleFeeText: 'LKR 10 / min',
    parkingText: 'Free', amenitiesText: 'Wi-Fi, Cafe',
    accessType: 'Public · Street Parking',
    network: 'Volt Charge · AC/DC Hybrid',
    priceHeadline: 'LKR 85.00',
    rates: { fast: 85, slow: 20 },
    maxChargingSpeedKw: 150, portsCount: 4,
    supportedModels: ['Nissan Leaf', 'MG ZS EV', 'Tesla Model 3/Y', 'BYD Atto 3'],
    amenities: ['wifi', 'cafe', 'parking', 'security'],
    connectors: [
      { name: 'CCS Combo 2', kw: '50kW', available: true },
      { name: 'Type 2 AC', kw: '7kW – 22kW', available: true },
    ],
  },
];

const run = async () => {
  await connectDB();
  await Station.deleteMany({});
  await Station.insertMany(sampleStations);
  console.log(`Seeded ${sampleStations.length} stations`);
  await mongoose.connection.close();
  process.exit(0);
};

run().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
